### PR TITLE
Support for makedepends base-devel check

### PR DESCRIPTION
**Pull request by D3vil0p3r**
In PKGBUILD, `makedepends` must not contain  `base-devel` dependencies according to https://wiki.archlinux.org/title/PKGBUILD#makedepends

Added support for checking the presence of `base-devel` dependencies in a PKGBUILD.
Added support for Python 3.12.

### CODE REVIEW

**Comment by D3vil0p3r** [comment]
The check fails by:
```
=====> .pre-commit-config.yaml is not a file
```
On the repository I see only `.pre-commit-hooks.yaml`.

**Comment by FFY00** [comment]
Sorry for the delay. This looks okay enough.

The CI status is because pre-commit.ci seems to have been enabled globally for my repos, and this project doesn't use pre-commit.

**Comment by D3vil0p3r** [comment]
Thanks for merging. Can you also please update the related PyPi Python package at https://pypi.org/project/pkgcheck-arch/#history ?

**Comment by FFY00** [comment]
Done :smile:

**Comment by D3vil0p3r** [comment]
I just noted `setup.py` uses `pbr` for versioning that relies on GitHub Release for retrieving versioning. Currently the tool, when installed by `setup.py`, returns an error when launched about the mismatch version, because it cannot find the tag and GitHub Release 0.1.3. This issue can be solved by creating a new release in this GitHub repo for `0.1.3` version.

Could you please create it in order to fix the current issue when installed by `setup.py`?

Thanks

**Pull request merged**
